[package]
name = "tetris"
version = "0.1.0"
authors = ["Stefan Blair <stblair@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"
rand = "0.8.0"